# Generated by Django 5.2 on 2025-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
